In [1]:
import tsfresh
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)
df = pd.DataFrame(np.concatenate([np.repeat(range(500),40)[:,np.newaxis],
                                  np.tile(range(40),500)[:,np.newaxis],
                                  np.random.randn(20000, 1)], axis=1), columns=["id", "time", "x"])

df

          id  time         x
0        0.0   0.0  0.496714
1        0.0   1.0 -0.138264
2        0.0   2.0  0.647689
3        0.0   3.0  1.523030
4        0.0   4.0 -0.234153
5        0.0   5.0 -0.234137
6        0.0   6.0  1.579213
7        0.0   7.0  0.767435
8        0.0   8.0 -0.469474
9        0.0   9.0  0.542560
10       0.0  10.0 -0.463418
11       0.0  11.0 -0.465730
12       0.0  12.0  0.241962
13       0.0  13.0 -1.913280
14       0.0  14.0 -1.724918
15       0.0  15.0 -0.562288
16       0.0  16.0 -1.012831
17       0.0  17.0  0.314247
18       0.0  18.0 -0.908024
19       0.0  19.0 -1.412304
20       0.0  20.0  1.465649
21       0.0  21.0 -0.225776
22       0.0  22.0  0.067528
23       0.0  23.0 -1.424748
24       0.0  24.0 -0.544383
25       0.0  25.0  0.110923
26       0.0  26.0 -1.150994
27       0.0  27.0  0.375698
28       0.0  28.0 -0.600639
29       0.0  29.0 -0.291694
...      ...   ...       ...
19970  499.0  10.0  1.085189
19971  499.0  11.0 -0.384582
19972  499.0  12.0 -0.881141
19973  499.0  13.0 -1.005713
19974  499.0  14.0 -1.064496
19975  499.0  15.0  0.659068
19976  499.0  16.0 -0.742746
19977  499.0  17.0 -1.033029
19978  499.0  18.0  0.713735
19979  499.0  19.0  0.327970
19980  499.0  20.0  0.962592
19981  499.0  21.0  0.512600
19982  499.0  22.0 -0.753112
19983  499.0  23.0  0.076102
19984  499.0  24.0  0.125133
19985  499.0  25.0 -0.919159
19986  499.0  26.0 -1.104625
19987  499.0  27.0 -0.680722
19988  499.0  28.0  2.036582
19989  499.0  29.0 -0.412744
19990  499.0  30.0  1.232867
19991  499.0  31.0 -0.468661
19992  499.0  32.0  0.888839
19993  499.0  33.0  0.902492
19994  499.0  34.0  0.952591
19995  499.0  35.0  0.387827
19996  499.0  36.0  1.377367
19997  499.0  37.0  0.378354
19998  499.0  38.0  1.713530
19999  499.0  39.0 -1.619920

[20000 rows x 3 columns]

In [3]:
ts = tsfresh.extract_features(df, column_id="id")
# ts_filtered = tsfresh.extract_relevant_features(df, y, column_id="id")

/usr/local/lib/python2.7/site-packages/pandas/computation/expressions.py:182: UserWarning: evaluating in Python space because the '*' operator is not supported by numexpr for the bool dtype, use '&' instead
  unsupported[op_str]))
/usr/local/lib/python2.7/site-packages/scipy/signal/spectral.py:772: UserWarning: nperseg = 256, is greater than input length = 40, using nperseg = 40
  'using nperseg = {1:d}'.format(nperseg, x.shape[-1]))

In [4]:
df.to_csv("df.csv", index=False)
ts.to_csv("ts.csv", index=False)
# ts_filtered.to_csv("ts_filtered.csv", index=False)